### ISSUE TITLE
Added support for ESP8266 and general optimizations (code attached)

### ISSUE THREAD

**Issue by messier433** [Andre-Schuiki/esphome_im350#6]
Hi,

main issue with the current version of the code is that it does not compile for ESP8266 since it has no Serial2 interface.
Better approach is to derive the class from the uart component.
Also the update method should not block the CPU for several 100ms until the message is completely received.

All these shortcomings (and general cleanup) are adressed in the attached code and an example config for ESP8266 is add with inverted RX line (no additional  transistor used on PCB)

[siemens_im350.zip](https://github.com/Andre-Schuiki/esphome_im350/files/13823563/siemens_im350.zip)
[siemens_im350_yaml.zip](https://github.com/Andre-Schuiki/esphome_im350/files/13823648/siemens_im350_yaml.zip)

**Comment by daniel89fhem** [comment]
Hi,

i wanted to use your solution for my smartmeter, but i'm getting error while making the binary file.
Here is the output of the generating:
`INFO ESPHome 2024.6.1
INFO Reading configuration /config/siemens_im350.yaml...
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1079, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1066, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 433, in command_compile
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 194, in write_cpp
    return write_cpp_file()
           ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 212, in write_cpp_file
    writer.write_cpp(code_s)
  File "/esphome/esphome/writer.py", line 344, in write_cpp
    copy_src_tree()
  File "/esphome/esphome/writer.py", line 236, in copy_src_tree
    source_files += component.resources
                    ^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/loader.py", line 109, in resources
    for r in importlib.resources.files(self.package).iterdir()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_common.py", line 22, in files
    return from_package(get_package(package))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_common.py", line 65, in from_package
    reader = spec.loader.get_resource_reader(spec.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_adapters.py", line 29, in get_resource_reader
    return CompatibilityFiles(self.spec)._native()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_adapters.py", line 155, in _native
    reader = self._reader
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/resources/_adapters.py", line 149, in _reader
    return self.spec.loader.get_resource_reader(self.spec.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1380, in get_resource_reader
  File "/usr/lib/python3.11/importlib/resources/readers.py", line 110, in __init__
    raise ValueError('Invalid path')
ValueError: Invalid path`

This also occurs, if I use the original files from Andre

Can you help me?

**Comment by daniel89fhem** [comment]
Hi,

I want to use your Code. My esp home sensor is up and running. But i didn't got any values from my Reader. Previously i used a other project, which worked fine. So my decrypting key is ok.
Maybe my wiring is wrong. Am I right, that with your Code only 1 resistor (pull up) is necessary between data Pin and 3.3V? I'm using a 4k7 resistor.

**Comment by daniel89fhem** [comment]
![Screenshot_20240620_150614_Samsung Internet](https://github.com/Andre-Schuiki/esphome_im350/assets/46073065/48193ab8-f199-4981-8679-7ca96e5a1556)

**Comment by LengTho** [comment]
Hello 

> Hi,
> 
> main issue with the current version of the code is that it does not compile for ESP8266 since it has no Serial2 interface. Better approach is to derive the class from the uart component. Also the update method should not block the CPU for several 100ms until the message is completely received.
> 
> All these shortcomings (and general cleanup) are adressed in the attached code and an example config for ESP8266 is add with inverted RX line (no additional transistor used on PCB)
> 
> [siemens_im350.zip](https://github.com/Andre-Schuiki/esphome_im350/files/13823563/siemens_im350.zip) [siemens_im350_yaml.zip](https://github.com/Andre-Schuiki/esphome_im350/files/13823648/siemens_im350_yaml.zip)


I've tried your code on a ESP8266 but i get an error:

  File "/usr/lib/python3.11/importlib/resources/readers.py", line 110, in __init__
    raise ValueError('Invalid path')
ValueError: Invalid path

The configuration is valid, but compiling the C++ fails. Do you know whats the problem?

**Comment by daniel89fhem** [comment]
Hi. I think you had the same Problem as I.
Here is the solution:
To get the project building you have to add an empty __init__.py file into component folder /custom_components/siemens_im350

**Comment by LengTho** [comment]
> Hi. I think you had the same Problem as I. Here is the solution: To get the project building you have to add an empty **init**.py file into component folder /custom_components/siemens_im350

Thank you for your hint, but this doesn't work for me. I still get the same error :(

**Comment by fabian-st** [comment]
> > Hi. I think you had the same Problem as I. Here is the solution: To get the project building you have to add an empty **init**.py file into component folder /custom_components/siemens_im350
> 
> Thank you for your hint, but this doesn't work for me. I still get the same error :(


Same goes for me, a fix would be much appreciated @daniel89fhem @messier433 

EDIT: file must named `__init__.py` that fixed it @LengTho
